app:
  env: local
  port: 8080
  app_name: gin-app
  app_url: 0.0.0.0


redis:
  DB: 1
  Addr: 127.0.0.1:6379
  Password:

jwt:
  SigningKey: "secret key"
  ExpiresTime:
  BufferTime:       # 缓冲时间
  Issuer: "douyin-demo" #签发人
  JwtBlacklistGracePeriod: 10 # 黑名单宽限时间

log:
  level: info # 日志等级
  root_dir: ./storage/logs # 日志根目录
  filename: douyin1.log # 日志文件名称
  format: console # 写入格式 可选json
  show_line: true # 是否显示调用行
  max_backups: 3 # 旧文件的最大个数
  max_size: 500 # 日志文件最大大小（MB）
  max_age: 28 # 旧文件的最大保留天数
  compress: true # 是否压缩


